version: "3"
networks:
    anilskynet:
volumes:
  anil-db-data:
  
services:
  redis:
    image: redis:alpine
    volumes:
      - anil-db-data:/data
    networks:
      anilskynet:
        aliases:
          - db
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    image: katacoda/redis-node-docker-example
    networks:
      - anilskynet
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=ANILWEB]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [node.role == worker]